import { StyleSheet } from "react-native";

import { colors } from "../constants/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  appContent: {
    flex: 1,
    minHeight: 0,
    backgroundColor: "#ffffff",
  },
  globalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 6,
    backgroundColor: "#ffffff",
  },
  logoWrap: {
    justifyContent: "center",
    minHeight: 54,
  },
  logoButton: {
    alignSelf: "flex-start",
  },
  logoText: {
    color: colors.brand,
    fontSize: 34,
    fontWeight: "800",
    fontStyle: "italic",
    letterSpacing: 0.5,
    transform: [{ rotate: "-4deg" }],
  },
  logoUnderlineWrap: {
    marginTop: -2,
    height: 14,
    justifyContent: "center",
  },
  logoUnderline: {
    width: 126,
    height: 4,
    borderRadius: 999,
    backgroundColor: colors.accent,
    marginLeft: 26,
  },
  logoDot: {
    position: "absolute",
    borderRadius: 999,
  },
  logoDotOne: {
    width: 8,
    height: 8,
    backgroundColor: colors.accent,
    left: 144,
    top: 1,
  },
  logoDotTwo: {
    width: 6,
    height: 6,
    backgroundColor: colors.brand,
    left: 158,
    top: 0,
  },
  logoDotThree: {
    width: 5,
    height: 5,
    backgroundColor: colors.accent,
    left: 170,
    top: 4,
  },
  menuButton: {
    width: 42,
    height: 42,
    borderRadius: 999,
    backgroundColor: "transparent",
    borderWidth: 0,
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
  },
  menuLine: {
    width: 22,
    height: 2,
    borderRadius: 999,
    backgroundColor: colors.text,
  },
  headerActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  bottomNav: {
    minHeight: 78,
    marginHorizontal: 14,
    marginBottom: 10,
    borderRadius: 34,
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    borderWidth: 1,
    borderColor: "rgba(223, 211, 191, 0.75)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 12,
    paddingVertical: 8,
    boxShadow: "0 -14px 34px rgba(15, 23, 42, 0.10)",
  },
  bottomNavItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    minHeight: 54,
  },
  bottomNavIconSlot: {
    width: 30,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  bottomNavNotificationDot: {
    position: "absolute",
    right: 1,
    top: 0,
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#ef4444",
    borderWidth: 1.5,
    borderColor: "#ffffff",
  },
  lineIconBox: {
    width: 28,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  homeIconRoof: {
    position: "absolute",
    top: 3,
    width: 16,
    height: 16,
    borderLeftWidth: 2,
    borderTopWidth: 2,
    borderRadius: 2,
    transform: [{ rotate: "45deg" }],
  },
  homeIconBase: {
    position: "absolute",
    bottom: 2,
    width: 15,
    height: 13,
    borderWidth: 2,
    borderTopWidth: 0,
    borderRadius: 3,
  },
  searchIconCircle: {
    width: 16,
    height: 16,
    borderRadius: 999,
    borderWidth: 2,
  },
  searchIconHandle: {
    position: "absolute",
    right: 4,
    bottom: 5,
    width: 9,
    height: 2,
    borderRadius: 999,
    transform: [{ rotate: "45deg" }],
  },
  bellIconBody: {
    width: 17,
    height: 18,
    borderWidth: 2,
    borderTopLeftRadius: 9,
    borderTopRightRadius: 9,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  bellIconClapper: {
    width: 5,
    height: 5,
    borderRadius: 999,
    marginTop: 2,
  },
  userIconHead: {
    width: 10,
    height: 10,
    borderRadius: 999,
    borderWidth: 2,
    marginBottom: 2,
  },
  userIconShoulder: {
    width: 18,
    height: 10,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  bottomNavLabel: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "800",
  },
  bottomNavLabelActive: {
    color: colors.accent,
  },
  bottomComposeButton: {
    width: 68,
    height: 68,
    borderRadius: 999,
    backgroundColor: "#0ea5a3",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    marginTop: 0,
    boxShadow: "0 12px 26px rgba(14, 165, 163, 0.28)",
  },
  bottomComposeIcon: {
    color: "#ffffff",
    fontSize: 23,
    fontWeight: "900",
  },
  bottomComposeLabel: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  container: {
    padding: 20,
    paddingTop: 12,
    paddingBottom: 104,
    gap: 18,
    backgroundColor: "#ffffff",
  },
  pageContainer: {
    padding: 20,
    paddingTop: 12,
    paddingBottom: 104,
    gap: 16,
    backgroundColor: "#ffffff",
  },
  timelineScreen: {
    flex: 1,
    minHeight: 0,
    paddingBottom: 0,
    gap: 10,
  },
  timelineIntroBar: {
    position: "relative",
    backgroundColor: "#ffffff",
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingTop: 26,
    paddingBottom: 22,
    gap: 10,
    borderWidth: 0,
    overflow: "hidden",
    minHeight: 166,
    boxShadow: "0 18px 44px rgba(15, 118, 110, 0.10)",
  },
  accordionTitleRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  accordionToggleText: {
    color: colors.accent,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "900",
  },
  timelineIntroTitle: {
    color: "#111827",
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "900",
    letterSpacing: -0.6,
  },
  timelineIntroText: {
    color: "#273142",
    fontSize: 14,
    lineHeight: 24,
    fontWeight: "600",
    maxWidth: 300,
  },
  searchPageContainer: {
    paddingBottom: 48,
  },
  menuOverlay: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.25)",
  },
  sideMenu: {
    width: 260,
    backgroundColor: colors.surface,
    borderLeftWidth: 1,
    borderLeftColor: colors.line,
    paddingHorizontal: 18,
    paddingTop: 86,
  },
  sideMenuContent: {
    paddingBottom: 24,
    gap: 10,
  },
  sideMenuHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  sideMenuTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "800",
  },
  sideMenuCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  sideMenuCloseButtonText: {
    color: colors.text,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "700",
  },
  sideMenuItem: {
    backgroundColor: "#fbfaf7",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  sideMenuItemText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "700",
  },
  heroCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 14,
  },
  pageHeaderCard: {
    backgroundColor: "#ffffff",
    borderRadius: 30,
    padding: 24,
    borderWidth: 0,
    gap: 12,
    boxShadow: "0 16px 34px rgba(15, 23, 42, 0.07)",
  },
  backButton: {
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.brandSoft,
  },
  backButtonText: {
    color: colors.brand,
    fontWeight: "700",
  },
  eyebrow: {
    color: colors.brand,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: colors.text,
    fontSize: 30,
    lineHeight: 38,
    fontWeight: "800",
  },
  heroText: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 24,
  },
  timelineSectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 50,
    height: 50,
    maxHeight: 50,
    paddingHorizontal: 4,
    paddingBottom: 0,
    paddingRight: 16,
    gap: 8,
  },
  timelineSectionScrollShell: {
    width: "100%",
    height: 50,
    minHeight: 50,
    maxHeight: 50,
    flexBasis: 50,
    flexGrow: 0,
    flexShrink: 0,
    alignSelf: "stretch",
    overflow: "hidden",
  },
  timelineSectionScroll: {
    width: "100%",
    height: 50,
    minHeight: 50,
    maxHeight: 50,
    flexBasis: 50,
    flexGrow: 0,
    flexShrink: 0,
    alignSelf: "stretch",
    overflow: "hidden",
  },
  timelineSectionChip: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: "rgba(209, 213, 219, 0.9)",
    boxShadow: "0 8px 22px rgba(17, 24, 39, 0.05)",
  },
  timelineSectionChipActive: {
    backgroundColor: "#0ea5a3",
    borderColor: colors.accent,
    boxShadow: "0 14px 28px rgba(14, 165, 163, 0.22)",
  },
  timelineSectionChipText: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
  },
  timelineSectionChipTextActive: {
    color: colors.surface,
  },
  timelinePager: {
    flex: 1,
    minHeight: 0,
  },
  timelinePage: {
    flex: 1,
  },
  timelineContentShell: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    marginTop: 0,
    paddingTop: 0,
  },
  timelineContentScroller: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    marginTop: 0,
  },
  timelinePageContent: {
    gap: 14,
    paddingTop: 0,
    paddingBottom: 18,
  },
  heroActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  primaryButton: {
    backgroundColor: colors.brand,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 999,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "700",
  },
  textLinkButton: {
    paddingHorizontal: 8,
    paddingVertical: 10,
    alignSelf: "center",
  },
  textLinkButtonText: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
  },
  secondaryButton: {
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 999,
  },
  secondaryButtonText: {
    color: colors.brand,
    fontWeight: "700",
  },
  ghostButton: {
    backgroundColor: colors.surface,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
  },
  ghostButtonText: {
    color: colors.text,
    fontWeight: "700",
  },
  disabledButton: {
    opacity: 0.7,
  },
  flowCard: {
    backgroundColor: "#fcf7ee",
    borderRadius: 22,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  practiceTemplateCard: {
    backgroundColor: "#fcf7ee",
    borderRadius: 22,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: colors.line,
  },
  inlineFieldGrid: {
    gap: 12,
  },
  practiceMenuBox: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    gap: 10,
    marginTop: 10,
  },
  practiceMenuHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  practiceMenuTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
  },
  practiceMenuRow: {
    gap: 4,
  },
  practiceMenuLabel: {
    color: colors.brand,
    fontSize: 12,
    fontWeight: "800",
  },
  practiceMenuValue: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "600",
  },
  flowTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
  },
  flowText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  flowHint: {
    color: colors.brand,
    fontSize: 13,
    fontWeight: "700",
  },
  authPanel: {
    backgroundColor: "#fbfaf7",
    borderRadius: 22,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  authPanelTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
  },
  authPanelText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  warningText: {
    color: colors.error,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "700",
  },
  feedbackBanner: {
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
  },
  feedbackSuccess: {
    backgroundColor: colors.successSoft,
    borderColor: "#86efac",
  },
  feedbackError: {
    backgroundColor: colors.errorSoft,
    borderColor: "#fca5a5",
  },
  feedbackText: {
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "700",
  },
  feedbackSuccessText: {
    color: colors.success,
  },
  feedbackErrorText: {
    color: colors.error,
  },
  roleCard: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    padding: 18,
    gap: 8,
    borderWidth: 1,
    borderColor: colors.line,
  },
  statsRow: {
    gap: 12,
  },
  statCard: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 4,
  },
  statLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "600",
  },
  statValue: {
    color: colors.text,
    fontSize: 28,
    fontWeight: "800",
  },
  statNote: {
    color: colors.brand,
    fontSize: 13,
    fontWeight: "600",
  },
  topShortcutGrid: {
    gap: 12,
  },
  shortcutCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 18,
    gap: 8,
    borderWidth: 0,
    boxShadow: "0 12px 30px rgba(15, 23, 42, 0.06)",
  },
  shortcutTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "800",
  },
  shortcutText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  pageIntroCard: {
    backgroundColor: "#ffffff",
    borderRadius: 28,
    padding: 18,
    gap: 6,
    borderWidth: 0,
    boxShadow: "0 12px 30px rgba(15, 23, 42, 0.06)",
  },
  searchHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 14,
  },
  searchBackButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    justifyContent: "center",
    alignItems: "center",
  },
  searchBackButtonText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
  },
  searchInputShell: {
    flex: 1,
    minHeight: 52,
    backgroundColor: colors.surface,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchIcon: {
    color: colors.muted,
    fontSize: 18,
    fontWeight: "700",
  },
  searchInput: {
    flex: 1,
    color: colors.text,
    fontSize: 17,
    fontWeight: "700",
    paddingVertical: 10,
  },
  searchTabsBar: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 12,
  },
  searchTabButton: {
    flex: 1,
    alignItems: "center",
    paddingTop: 14,
    paddingBottom: 10,
    gap: 10,
  },
  searchTabText: {
    color: colors.muted,
    fontSize: 15,
    fontWeight: "700",
  },
  searchTabTextActive: {
    color: colors.text,
  },
  searchTabUnderline: {
    width: 64,
    height: 4,
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  searchFilterBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 6,
  },
  searchFilterChip: {
    backgroundColor: colors.surface,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  searchFilterChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  searchFilterChipText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
  },
  searchFilterChipTextActive: {
    color: "#ffffff",
  },
  todayMenuSearchCard: {
    marginHorizontal: 20,
    marginTop: 8,
    marginBottom: 12,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    padding: 16,
    gap: 10,
  },
  todayMenuSearchTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
  },
  todayMenuSearchText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "600",
  },
  searchResultStack: {
    gap: 0,
  },
  searchPostCard: {
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  searchPostTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  searchAvatar: {
    width: 52,
    height: 52,
    borderRadius: 999,
    backgroundColor: colors.brandSoft,
    justifyContent: "center",
    alignItems: "center",
  },
  searchAvatarText: {
    color: colors.brand,
    fontSize: 18,
    fontWeight: "800",
  },
  searchPostBody: {
    flex: 1,
    gap: 6,
  },
  searchPostAuthor: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
  },
  searchPostMeta: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "600",
  },
  searchSourceBadge: {
    alignSelf: "flex-start",
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  searchSourceBadgeText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
  },
  searchPostTitle: {
    color: colors.text,
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "800",
  },
  searchTopicStack: {
    gap: 0,
  },
  searchTopicCard: {
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    paddingHorizontal: 20,
    paddingVertical: 18,
    gap: 6,
  },
  searchTopicLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  searchTopicTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: "800",
  },
  searchTopicMeta: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  searchAccountCard: {
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  searchAccountBody: {
    flex: 1,
    gap: 8,
  },
  searchAccountHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  searchAccountTextWrap: {
    flex: 1,
    gap: 2,
  },
  searchFollowButton: {
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderWidth: 1,
  },
  searchFollowButtonPrimary: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  searchFollowButtonFollowing: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  searchFollowButtonText: {
    fontWeight: "800",
  },
  searchFollowButtonTextPrimary: {
    color: "#ffffff",
  },
  searchFollowButtonTextFollowing: {
    color: colors.accent,
  },
  filterSummaryCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  filterSummaryTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
  },
  sectionHeader: {
    gap: 4,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: "800",
  },
  sectionSubtitle: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  stack: {
    gap: 14,
  },
  registrationCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 20,
    gap: 16,
    borderWidth: 0,
    boxShadow: "0 12px 30px rgba(15, 23, 42, 0.06)",
  },
  registrationFlowCard: {
    backgroundColor: colors.brandSoft,
    borderRadius: 20,
    padding: 18,
    gap: 14,
    borderWidth: 1,
    borderColor: colors.line,
  },
  registrationFlowText: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 24,
    fontWeight: "600",
  },
  inlineButtonRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  formGroup: {
    gap: 8,
  },
  formLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  formLabel: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
  },
  formDetail: {
    color: colors.brand,
    fontSize: 12,
    fontWeight: "700",
  },
  fieldSupport: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
  },
  sportSelectorGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  sportGroupStack: {
    gap: 12,
  },
  sportGroupCard: {
    backgroundColor: "#fcf7ee",
    borderRadius: 18,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  sportGroupTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
  },
  sportSelectorChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: "#fbfaf7",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  sportSelectorChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  sportSelectorChipText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
  },
  sportSelectorChipTextActive: {
    color: "#ffffff",
  },
  sportChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  sportChip: {
    backgroundColor: "#fff0dc",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  sportChipText: {
    color: colors.brand,
    fontSize: 12,
    fontWeight: "700",
  },
  sportChipActive: {
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  sportChipActiveText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
  },
  imagePickerCard: {
    minHeight: 144,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: "#fbfaf7",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarPlaceholder: {
    padding: 20,
    alignItems: "center",
    gap: 8,
  },
  avatarPlaceholderText: {
    color: colors.accent,
    fontSize: 16,
    fontWeight: "800",
  },
  avatarPreview: {
    width: "100%",
    height: 180,
  },
  coverPreview: {
    width: "100%",
    height: 180,
  },
  removeImageButton: {
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.errorSoft,
  },
  removeImageButtonText: {
    color: colors.error,
    fontSize: 13,
    fontWeight: "800",
  },
  input: {
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: "#fbfaf7",
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: colors.text,
    fontSize: 14,
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  linkStack: {
    gap: 12,
  },
  linkCard: {
    backgroundColor: "#fcf7ee",
    borderRadius: 18,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  linkIndex: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
  },
  addButton: {
    alignSelf: "flex-start",
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  addButtonText: {
    color: colors.accent,
    fontWeight: "800",
  },
  registrationFooter: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    paddingTop: 4,
  },
  accountDeleteSection: {
    gap: 10,
    marginTop: 8,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  accountDeleteTitle: {
    color: colors.error,
    fontSize: 15,
    fontWeight: "800",
  },
  accountDeleteBody: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 22,
  },
  accountDeleteButton: {
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.error,
    backgroundColor: colors.errorSoft,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  accountDeleteButtonText: {
    color: colors.error,
    fontSize: 14,
    fontWeight: "800",
  },
  legalSection: {
    gap: 8,
    paddingBottom: 8,
  },
  legalSectionTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
  },
  legalSectionBody: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  mediaActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  mediaPreviewStack: {
    gap: 12,
  },
  mediaPreviewCard: {
    backgroundColor: "#fcf7ee",
    borderRadius: 18,
    padding: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  mediaPreviewImage: {
    width: "100%",
    height: 220,
    borderRadius: 14,
    backgroundColor: colors.brandSoft,
  },
  mediaPreviewVideo: {
    minHeight: 120,
    borderRadius: 14,
    backgroundColor: colors.brandSoft,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
    gap: 6,
  },
  mediaRemoveButton: {
    alignSelf: "flex-start",
    backgroundColor: colors.errorSoft,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  mediaRemoveButtonText: {
    color: colors.error,
    fontSize: 12,
    fontWeight: "800",
  },
  postTargetRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  postTargetChip: {
    backgroundColor: "#fbfaf7",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  postTargetChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  postTargetChipText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  postTargetChipTextActive: {
    color: "#ffffff",
  },
  postCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 18,
    gap: 14,
    borderWidth: 0,
    boxShadow: "0 14px 36px rgba(15, 23, 42, 0.08)",
  },
  detailTapArea: {
    gap: 12,
  },
  postHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  authorRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  authorAvatar: {
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: "#ffe4b8",
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
  },
  authorAvatarText: {
    color: colors.brand,
    fontSize: 18,
    fontWeight: "800",
  },
  authorTextBlock: {
    flex: 1,
    gap: 2,
  },
  authorName: {
    color: "#111827",
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "900",
  },
  cardTitle: {
    color: "#111827",
    fontSize: 20,
    lineHeight: 29,
    fontWeight: "900",
    letterSpacing: -0.25,
  },
  cardMeta: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 4,
  },
  cardBody: {
    color: "#273142",
    fontSize: 15,
    lineHeight: 25,
  },
  richTextStack: {
    gap: 6,
  },
  richTextStackCompact: {
    gap: 4,
  },
  richTextSpacer: {
    height: 8,
  },
  richTextBold: {
    fontWeight: "800",
  },
  richQuoteBlock: {
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
    paddingLeft: 12,
    backgroundColor: "#f7fafc",
    borderRadius: 12,
    paddingVertical: 8,
    paddingRight: 10,
  },
  richListRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  richBullet: {
    color: colors.brand,
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 24,
  },
  richListText: {
    flex: 1,
  },
  richTextCompact: {
    fontSize: 14,
    lineHeight: 21,
  },
  richToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  richToolbarButton: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  richToolbarButtonText: {
    color: colors.brand,
    fontSize: 12,
    fontWeight: "800",
  },
  richEditorInput: {
    minHeight: 180,
    textAlignVertical: "top",
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    lineHeight: 24,
    color: colors.text,
  },
  mediaGallery: {
    gap: 10,
  },
  postMediaImage: {
    width: "100%",
    height: 240,
    borderRadius: 18,
    backgroundColor: colors.brandSoft,
  },
  postMediaImageCompact: {
    height: 180,
  },
  videoCard: {
    backgroundColor: "#f7fafc",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    gap: 6,
  },
  videoCardLabel: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
  },
  videoCardName: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  pill: {
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#0ea5a3",
    flexShrink: 0,
  },
  pillText: {
    color: "#0f766e",
    fontWeight: "800",
    fontSize: 12,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  tag: {
    backgroundColor: colors.brandSoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tagText: {
    color: colors.brand,
    fontSize: 12,
    fontWeight: "700",
  },
  metricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: "#eef2f7",
    paddingTop: 12,
  },
  metricButton: {
    backgroundColor: "#f8fafc",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  metricButtonActive: {
    backgroundColor: "#fff0dc",
  },
  metricChip: {
    backgroundColor: "#f8fafc",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  metricText: {
    color: colors.text,
    fontWeight: "700",
    fontSize: 13,
  },
  metricTextActive: {
    color: colors.brand,
  },
  replyList: {
    gap: 8,
    paddingTop: 2,
  },
  replyItem: {
    backgroundColor: "#f7fafc",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  replyAuthor: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
  },
  replyBody: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 20,
  },
  replyBodyCompact: {
    fontSize: 12,
    lineHeight: 18,
  },
  questionCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 18,
    gap: 12,
    borderWidth: 0,
    boxShadow: "0 14px 36px rgba(15, 23, 42, 0.08)",
  },
  categoryText: {
    color: colors.brand,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  bestAnswerBox: {
    backgroundColor: "#f7fafc",
    borderRadius: 18,
    padding: 16,
    gap: 8,
  },
  bestAnswerLabel: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
  },
  expertCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: colors.line,
  },
  scoreCard: {
    backgroundColor: colors.brandSoft,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: "center",
    minWidth: 90,
  },
  scoreValue: {
    color: colors.brand,
    fontSize: 20,
    fontWeight: "800",
  },
  scoreLabel: {
    color: colors.brand,
    fontSize: 11,
    fontWeight: "700",
  },
  expertMetrics: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  expertMetricBox: {
    flex: 1,
    minWidth: 130,
    backgroundColor: "#f7fafc",
    borderRadius: 18,
    padding: 14,
  },
  expertMetricValue: {
    color: colors.text,
    fontSize: 21,
    fontWeight: "800",
  },
  expertMetricLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  promoText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  communityCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 18,
    gap: 14,
    borderWidth: 0,
    boxShadow: "0 14px 36px rgba(15, 23, 42, 0.08)",
  },
  profileShell: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.line,
  },
  profileBanner: {
    height: 180,
    backgroundColor: "#d8c7ad",
  },
  profileBannerImage: {
    width: "100%",
    height: 180,
  },
  profileTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingHorizontal: 20,
    marginTop: -44,
  },
  userProfileActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  userProfileAvatar: {
    backgroundColor: colors.surface,
  },
  profileIconButton: {
    backgroundColor: colors.surface,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  profileIconButtonText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  profileFollowButton: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 22,
    paddingVertical: 12,
  },
  profileFollowButtonPrimary: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  profileFollowButtonFollowing: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.brand,
  },
  profileFollowButtonText: {
    fontSize: 14,
    fontWeight: "800",
  },
  profileFollowButtonTextPrimary: {
    color: "#ffffff",
  },
  profileFollowButtonTextFollowing: {
    color: colors.brand,
  },
  profileAvatar: {
    width: 92,
    height: 92,
    borderRadius: 999,
    backgroundColor: colors.brand,
    borderWidth: 5,
    borderColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  profileAvatarText: {
    color: "#fff7ed",
    fontSize: 28,
    fontWeight: "800",
  },
  profileEditButton: {
    backgroundColor: colors.surface,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  profileEditButtonText: {
    color: colors.text,
    fontWeight: "700",
  },
  profileBody: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 18,
    gap: 8,
  },
  profileNameRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  profileName: {
    color: colors.text,
    fontSize: 28,
    fontWeight: "800",
  },
  profileHandle: {
    color: colors.muted,
    fontSize: 16,
    fontWeight: "600",
  },
  profileRole: {
    color: colors.brand,
    fontSize: 13,
    fontWeight: "700",
  },
  profileBio: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 24,
  },
  coachProfileDetailBox: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceStrong,
    padding: 14,
    gap: 10,
    marginTop: 4,
  },
  coachProfileDetailTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
  },
  coachProfileDetailRow: {
    gap: 4,
  },
  coachProfileDetailLabel: {
    color: colors.brand,
    fontSize: 12,
    fontWeight: "800",
  },
  coachProfileDetailValue: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "600",
  },
  profileJoined: {
    color: colors.muted,
    fontSize: 14,
  },
  profileFollowRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    paddingTop: 4,
  },
  badgeSection: {
    gap: 10,
    paddingTop: 6,
  },
  badgeSectionTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
  },
  badgeLauncher: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  badgePreviewRow: {
    flexDirection: "row",
    gap: 10,
  },
  badgeLauncherTextWrap: {
    flex: 1,
    gap: 2,
  },
  badgeLauncherTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
  },
  badgeLauncherMeta: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  badgeStackedWrap: {
    alignItems: "center",
    gap: 4,
  },
  kBadge: {
    width: 44,
    height: 44,
    borderRadius: 999,
    borderWidth: 2,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  kBadgeLarge: {
    width: 56,
    height: 56,
  },
  kBadgeInner: {
    width: "78%",
    height: "78%",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.65)",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  badgeBronze: {
    backgroundColor: "#c87a41",
    borderColor: "#8c4b1f",
  },
  badgeSilver: {
    backgroundColor: "#c2ccd8",
    borderColor: "#7c8797",
  },
  badgeGold: {
    backgroundColor: "#efc24b",
    borderColor: "#a46c00",
  },
  kBadgeText: {
    color: "#fffdf8",
    fontSize: 20,
    fontWeight: "900",
    textShadowColor: "rgba(0,0,0,0.18)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  badgeRibbon: {
    minWidth: 24,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: colors.text,
    justifyContent: "center",
    alignItems: "center",
  },
  badgeRibbonLarge: {
    paddingHorizontal: 8,
    minWidth: 58,
  },
  badgeRibbonText: {
    color: "#ffffff",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  badgeTierText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: "800",
  },
  badgeLabelText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
  },
  badgeDescriptionText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  badgeModalStack: {
    gap: 12,
  },
  badgeModalCard: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    borderRadius: 18,
    borderWidth: 1.5,
    padding: 12,
  },
  badgeModalCardBronze: {
    borderColor: "#d4a07c",
    backgroundColor: "#fff4ea",
  },
  badgeModalCardSilver: {
    borderColor: "#b8c2cf",
    backgroundColor: "#f7fafc",
  },
  badgeModalCardGold: {
    borderColor: "#e5c364",
    backgroundColor: "#fff8de",
  },
  badgeModalTextWrap: {
    flex: 1,
    gap: 2,
  },
  profileFeedButton: {
    alignSelf: "flex-start",
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginTop: 8,
  },
  profileFeedButtonText: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
  },
  profileFollowText: {
    color: colors.muted,
    fontSize: 15,
  },
  profileFollowValue: {
    color: colors.text,
    fontWeight: "800",
  },
  profileTabBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: colors.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    overflow: "hidden",
  },
  profileTabItem: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  profileTabItemActive: {
    borderBottomWidth: 3,
    borderBottomColor: colors.accent,
  },
  profileTabText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "700",
  },
  profileTabTextActive: {
    color: colors.text,
  },
  profilePostCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.line,
  },
  repostNoticeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  repostNoticeIcon: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "800",
  },
  repostNoticeText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  profilePostHeader: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  profileSourceBadge: {
    marginLeft: "auto",
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  profileSourceBadgeText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
  },
  profilePostMiniAvatar: {
    width: 44,
    height: 44,
    borderRadius: 999,
    backgroundColor: colors.brandSoft,
    justifyContent: "center",
    alignItems: "center",
  },
  profilePostMiniAvatarText: {
    color: colors.brand,
    fontWeight: "800",
  },
  postDetailShell: {
    gap: 16,
  },
  postDetailHeaderBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  postDetailHeaderTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "800",
  },
  postDetailHeaderSpacer: {
    width: 56,
  },
  postDetailCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 24,
    gap: 16,
  },
  postDetailAuthorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  postDetailAvatar: {
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: colors.brandSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  postDetailAvatarText: {
    color: colors.accent,
    fontSize: 22,
    fontWeight: "800",
  },
  postDetailAuthorText: {
    flex: 1,
    gap: 4,
  },
  postDetailAuthorName: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "800",
  },
  postDetailAuthorMeta: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "600",
  },
  postDetailTitle: {
    color: colors.text,
    fontSize: 28,
    lineHeight: 38,
    fontWeight: "800",
  },
  postDetailBody: {
    color: colors.text,
    fontSize: 20,
    lineHeight: 32,
  },
  postDetailMetaLine: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "600",
  },
  postDeleteButton: {
    alignSelf: "flex-start",
    backgroundColor: colors.errorSoft,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  postDeleteButtonText: {
    color: colors.error,
    fontSize: 13,
    fontWeight: "800",
  },
  postDetailMetricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingTop: 4,
  },
  postDetailReplyComposer: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
  },
  postDetailReplyComposerBody: {
    flex: 1,
    gap: 12,
  },
  postDetailReplyAvatar: {
    width: 44,
    height: 44,
    borderRadius: 999,
    backgroundColor: colors.brandSoft,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  postDetailReplyAvatarText: {
    color: colors.accent,
    fontSize: 18,
    fontWeight: "800",
  },
  postDetailReplyInput: {
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 16,
  },
  inlineCountText: {
    alignSelf: "flex-end",
    color: colors.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  postDetailReplyActionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  postDetailReplyPlaceholder: {
    color: colors.muted,
    fontSize: 16,
    fontWeight: "600",
  },
  postDetailReplyButton: {
    backgroundColor: colors.accent,
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  postDetailReplyButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  postDetailReplies: {
    gap: 0,
  },
  postDetailReplyCard: {
    position: "relative",
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    paddingVertical: 18,
    paddingHorizontal: 10,
  },
  postDetailThreadLine: {
    position: "absolute",
    left: 31,
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: colors.line,
  },
  postDetailReplyRow: {
    flexDirection: "row",
    gap: 12,
  },
  postDetailReplyContent: {
    flex: 1,
    gap: 6,
  },
  replyMetricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  postDetailReplyAuthor: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
  },
  postDetailReplyText: {
    color: colors.text,
    fontSize: 17,
    lineHeight: 28,
  },
  bestAnswerInlineBadge: {
    alignSelf: "flex-start",
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  bestAnswerInlineBadgeText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
  },
  bestAnswerSelectButton: {
    alignSelf: "flex-start",
    backgroundColor: colors.brandSoft,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  bestAnswerSelectButtonText: {
    color: colors.brand,
    fontSize: 13,
    fontWeight: "800",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(22, 28, 45, 0.26)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(22, 28, 45, 0.32)",
    justifyContent: "center",
    padding: 24,
  },
  modalFill: {
    ...StyleSheet.absoluteFillObject,
  },
  modalCard: {
    width: "100%",
    maxWidth: 460,
    backgroundColor: colors.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 24,
    gap: 16,
  },
  modalTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: "800",
  },
  modalBody: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 24,
  },
  modalButtonRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  modalSecondaryButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: colors.surface,
  },
  modalSecondaryButtonText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
  },
  modalPrimaryButton: {
    borderRadius: 999,
    backgroundColor: colors.accent,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  modalPrimaryButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  modalDangerButton: {
    borderRadius: 999,
    backgroundColor: colors.error,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  modalDangerButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  userActionMenuCard: {
    width: "100%",
    maxWidth: 460,
    alignSelf: "center",
    backgroundColor: colors.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 24,
    gap: 14,
  },
  userActionMenuItem: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: "#fbfaf7",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  userActionMenuItemText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
  },
  userActionMenuSubmit: {
    alignSelf: "stretch",
    alignItems: "center",
  },
  profilePostHeaderText: {
    gap: 2,
  },
  profilePostName: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
  },
  profilePostMeta: {
    color: colors.muted,
    fontSize: 13,
  },
  profilePostTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "800",
  },
  profilePostMetrics: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
  },
  profileMetricText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  communityButton: {
    alignSelf: "flex-start",
    backgroundColor: colors.accent,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  communityButtonText: {
    color: "#ffffff",
    fontWeight: "700",
  },
  flowOptionTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "800",
  },
  flowOptionText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
  },
  flowOptionCta: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 4,
  },
  mediaWarningText: {
    color: "#b42318",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  externalLinkModalUrl: {
    color: colors.accent,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 8,
    marginBottom: 16,
  },
  modalActionRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  notificationCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 22,
    gap: 8,
  },
  notificationTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
  },
  notificationBody: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 22,
  },
  notificationMeta: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  externalLinksRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  externalLinkChip: {
    borderRadius: 999,
    backgroundColor: "#e8f5f2",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  externalLinkChipText: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
  },
  pinnedNoticeRow: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: "#fff1c7",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  pinnedNoticeText: {
    color: "#9a6700",
    fontSize: 12,
    fontWeight: "800",
  },
  inlineActionButton: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: colors.surfaceStrong,
  },
  inlineActionButtonText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  userControlRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  richTextLink: {
    color: colors.accent,
    textDecorationLine: "underline",
  },
  linkPreviewCard: {
    marginTop: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: "#f7faf9",
    padding: 14,
    gap: 4,
  },
  linkPreviewDomain: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  linkPreviewUrl: {
    color: colors.accent,
    fontSize: 12,
    lineHeight: 18,
  },
  linkPreviewHint: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  expandToggleText: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
    marginTop: 8,
  },
});
